/*
  Creator: Will Hellinger
  Period: 1
  School: Lake Travis Highschool
*/

import java.lang.Math;
public class Passwords{
  public static void main(String [] args){
    String[] possible_characters = {"abcdefghijklmnopqrstuvwxyz", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", "1234567890"};
    String pattern_options = "lUn"; //l: lowercase | U: Uppercase | n: number
    String pattern = "lUnllnlU"; //l: lowercase | U: Uppercase | n: number
    String password = "";
    for (int a = 0; a < pattern.length(); a++) {
      for (int b = 0; b < pattern_options.length(); b++) {
        if (String.valueOf(pattern_options.charAt(b)).equals(String.valueOf(pattern.charAt(a)))){
          password += possible_characters[b].charAt((int)(Math.random() * (possible_characters[b].length() - 1)));
        }
      }
    }
    System.out.println(password + "\nPassword Generated by Will Hellinger");
  }
}